POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndobyIsImlkIjoiNjJlNmMzZDcwZGYzOWQ0NjUwYWI0MDMwIiwiaWF0IjoxNjU5MjkwNjA2fQ.qscZIQ0cuuLDxVMObFWuhp8auL0isObYS3DCodrf8hU

{
	"title": "checking 4.20",
	"url": "dasda",
	"likes": 3
}
###
POST  http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
	"title": "aaw",
	"author": "bsss",
	"url": "wh32er",
	"likes": 4,
	"userId": "62e3c2bd17bc73a5fd518865"
}
###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
	"username": "who",
	"password": "meson"
}
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
	"username": "who",
	"name": "sup",
	"password": "meson"
}
###
PUT http://localhost:3003/api/blogs/5a422aa71b54a676234d17f8
content-type: application/json

{
	"likes": 5
}
###
GET http://localhost:3003/
###
DELETE http://localhost:3003/api/blogs/5a422aa71b54a676234d17f8
